// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drug_units.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countDrugUnitsByDrug = `-- name: CountDrugUnitsByDrug :one
SELECT count(*)
FROM drug_units
WHERE drug_id = $1
`

func (q *Queries) CountDrugUnitsByDrug(ctx context.Context, drugID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDrugUnitsByDrug, drugID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDrugUnit = `-- name: CreateDrugUnit :one
INSERT INTO drug_units (drug_id, serial_number, status)
VALUES ($1, $2, $3)
RETURNING id, drug_id, serial_number, status, created_at, updated_at
`

type CreateDrugUnitParams struct {
	DrugID       uuid.UUID      `json:"drug_id"`
	SerialNumber string         `json:"serial_number"`
	Status       DrugUnitStatus `json:"status"`
}

func (q *Queries) CreateDrugUnit(ctx context.Context, arg CreateDrugUnitParams) (DrugUnit, error) {
	row := q.db.QueryRow(ctx, createDrugUnit, arg.DrugID, arg.SerialNumber, arg.Status)
	var i DrugUnit
	err := row.Scan(
		&i.ID,
		&i.DrugID,
		&i.SerialNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDrugUnit = `-- name: GetDrugUnit :one
SELECT id, drug_id, serial_number, status, created_at, updated_at
FROM drug_units
WHERE id = $1
`

func (q *Queries) GetDrugUnit(ctx context.Context, id uuid.UUID) (DrugUnit, error) {
	row := q.db.QueryRow(ctx, getDrugUnit, id)
	var i DrugUnit
	err := row.Scan(
		&i.ID,
		&i.DrugID,
		&i.SerialNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDrugUnitBySerial = `-- name: GetDrugUnitBySerial :one
SELECT du.id, du.drug_id, du.serial_number, du.status, du.created_at, du.updated_at,
       d.name AS drug_name,
       d.generic_name AS drug_generic_name,
       d.batch_number AS drug_batch_number,
       d.nafdac_number AS drug_nafdac_number,
       d.manufacturing_date AS drug_manufacturing_date,
       d.expiry_date AS drug_expiry_date,
       d.status AS drug_status,
       m.name AS manufacturer_name
FROM drug_units du
JOIN drugs d ON du.drug_id = d.id
JOIN manufacturers m ON d.manufacturer_id = m.id
WHERE du.serial_number = $1
`

type GetDrugUnitBySerialRow struct {
	ID                    uuid.UUID      `json:"id"`
	DrugID                uuid.UUID      `json:"drug_id"`
	SerialNumber          string         `json:"serial_number"`
	Status                DrugUnitStatus `json:"status"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	DrugName              string         `json:"drug_name"`
	DrugGenericName       string         `json:"drug_generic_name"`
	DrugBatchNumber       string         `json:"drug_batch_number"`
	DrugNafdacNumber      string         `json:"drug_nafdac_number"`
	DrugManufacturingDate time.Time      `json:"drug_manufacturing_date"`
	DrugExpiryDate        time.Time      `json:"drug_expiry_date"`
	DrugStatus            DrugStatus     `json:"drug_status"`
	ManufacturerName      string         `json:"manufacturer_name"`
}

func (q *Queries) GetDrugUnitBySerial(ctx context.Context, serialNumber string) (GetDrugUnitBySerialRow, error) {
	row := q.db.QueryRow(ctx, getDrugUnitBySerial, serialNumber)
	var i GetDrugUnitBySerialRow
	err := row.Scan(
		&i.ID,
		&i.DrugID,
		&i.SerialNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DrugName,
		&i.DrugGenericName,
		&i.DrugBatchNumber,
		&i.DrugNafdacNumber,
		&i.DrugManufacturingDate,
		&i.DrugExpiryDate,
		&i.DrugStatus,
		&i.ManufacturerName,
	)
	return i, err
}

const listDrugUnitsByDrug = `-- name: ListDrugUnitsByDrug :many
SELECT id, drug_id, serial_number, status, created_at, updated_at
FROM drug_units
WHERE drug_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDrugUnitsByDrugParams struct {
	DrugID uuid.UUID `json:"drug_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListDrugUnitsByDrug(ctx context.Context, arg ListDrugUnitsByDrugParams) ([]DrugUnit, error) {
	rows, err := q.db.Query(ctx, listDrugUnitsByDrug, arg.DrugID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DrugUnit{}
	for rows.Next() {
		var i DrugUnit
		if err := rows.Scan(
			&i.ID,
			&i.DrugID,
			&i.SerialNumber,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDrugUnitStatus = `-- name: UpdateDrugUnitStatus :one
UPDATE drug_units
SET status = $2
WHERE id = $1
RETURNING id, drug_id, serial_number, status, created_at, updated_at
`

type UpdateDrugUnitStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status DrugUnitStatus `json:"status"`
}

func (q *Queries) UpdateDrugUnitStatus(ctx context.Context, arg UpdateDrugUnitStatusParams) (DrugUnit, error) {
	row := q.db.QueryRow(ctx, updateDrugUnitStatus, arg.ID, arg.Status)
	var i DrugUnit
	err := row.Scan(
		&i.ID,
		&i.DrugID,
		&i.SerialNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
