// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drugs.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDrugs = `-- name: CountDrugs :one
SELECT count(*)
FROM drugs d
WHERE
    ($1::text IS NULL OR d.name ILIKE '%' || $1::text || '%')
    AND ($2::text IS NULL OR d.generic_name ILIKE '%' || $2::text || '%')
    AND ($3::text IS NULL OR d.batch_number = $3::text)
    AND ($4::drug_status IS NULL OR d.status = $4::drug_status)
    AND ($5::uuid IS NULL OR d.manufacturer_id = $5::uuid)
    AND ($6::date IS NULL OR d.expiry_date <= $6::date)
    AND ($7::date IS NULL OR d.expiry_date >= $7::date)
`

type CountDrugsParams struct {
	Name           pgtype.Text    `json:"name"`
	GenericName    pgtype.Text    `json:"generic_name"`
	BatchNumber    pgtype.Text    `json:"batch_number"`
	Status         NullDrugStatus `json:"status"`
	ManufacturerID pgtype.UUID    `json:"manufacturer_id"`
	ExpiryBefore   pgtype.Date    `json:"expiry_before"`
	ExpiryAfter    pgtype.Date    `json:"expiry_after"`
}

func (q *Queries) CountDrugs(ctx context.Context, arg CountDrugsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDrugs,
		arg.Name,
		arg.GenericName,
		arg.BatchNumber,
		arg.Status,
		arg.ManufacturerID,
		arg.ExpiryBefore,
		arg.ExpiryAfter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDrug = `-- name: CreateDrug :one
INSERT INTO drugs (
    name, generic_name, manufacturer_id, batch_number,
    nafdac_number, manufacturing_date, expiry_date,
    quantity, status, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, generic_name, manufacturer_id, batch_number, nafdac_number, manufacturing_date, expiry_date, quantity, status, created_by, created_at, updated_at
`

type CreateDrugParams struct {
	Name              string     `json:"name"`
	GenericName       string     `json:"generic_name"`
	ManufacturerID    uuid.UUID  `json:"manufacturer_id"`
	BatchNumber       string     `json:"batch_number"`
	NafdacNumber      string     `json:"nafdac_number"`
	ManufacturingDate time.Time  `json:"manufacturing_date"`
	ExpiryDate        time.Time  `json:"expiry_date"`
	Quantity          int32      `json:"quantity"`
	Status            DrugStatus `json:"status"`
	CreatedBy         uuid.UUID  `json:"created_by"`
}

func (q *Queries) CreateDrug(ctx context.Context, arg CreateDrugParams) (Drug, error) {
	row := q.db.QueryRow(ctx, createDrug,
		arg.Name,
		arg.GenericName,
		arg.ManufacturerID,
		arg.BatchNumber,
		arg.NafdacNumber,
		arg.ManufacturingDate,
		arg.ExpiryDate,
		arg.Quantity,
		arg.Status,
		arg.CreatedBy,
	)
	var i Drug
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GenericName,
		&i.ManufacturerID,
		&i.BatchNumber,
		&i.NafdacNumber,
		&i.ManufacturingDate,
		&i.ExpiryDate,
		&i.Quantity,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDrug = `-- name: GetDrug :one
SELECT d.id, d.name, d.generic_name, d.manufacturer_id, d.batch_number, d.nafdac_number, d.manufacturing_date, d.expiry_date, d.quantity, d.status, d.created_by, d.created_at, d.updated_at,
       m.name AS manufacturer_name
FROM drugs d
JOIN manufacturers m ON d.manufacturer_id = m.id
WHERE d.id = $1
`

type GetDrugRow struct {
	ID                uuid.UUID  `json:"id"`
	Name              string     `json:"name"`
	GenericName       string     `json:"generic_name"`
	ManufacturerID    uuid.UUID  `json:"manufacturer_id"`
	BatchNumber       string     `json:"batch_number"`
	NafdacNumber      string     `json:"nafdac_number"`
	ManufacturingDate time.Time  `json:"manufacturing_date"`
	ExpiryDate        time.Time  `json:"expiry_date"`
	Quantity          int32      `json:"quantity"`
	Status            DrugStatus `json:"status"`
	CreatedBy         uuid.UUID  `json:"created_by"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	ManufacturerName  string     `json:"manufacturer_name"`
}

func (q *Queries) GetDrug(ctx context.Context, id uuid.UUID) (GetDrugRow, error) {
	row := q.db.QueryRow(ctx, getDrug, id)
	var i GetDrugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GenericName,
		&i.ManufacturerID,
		&i.BatchNumber,
		&i.NafdacNumber,
		&i.ManufacturingDate,
		&i.ExpiryDate,
		&i.Quantity,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManufacturerName,
	)
	return i, err
}

const getDrugByManufacturerAndBatch = `-- name: GetDrugByManufacturerAndBatch :one
SELECT id FROM drugs
WHERE manufacturer_id = $1 AND batch_number = $2
`

type GetDrugByManufacturerAndBatchParams struct {
	ManufacturerID uuid.UUID `json:"manufacturer_id"`
	BatchNumber    string    `json:"batch_number"`
}

func (q *Queries) GetDrugByManufacturerAndBatch(ctx context.Context, arg GetDrugByManufacturerAndBatchParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDrugByManufacturerAndBatch, arg.ManufacturerID, arg.BatchNumber)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getExpiredActiveDrugs = `-- name: GetExpiredActiveDrugs :many
SELECT id, name, batch_number, expiry_date
FROM drugs
WHERE status = 'active' AND expiry_date < CURRENT_DATE
LIMIT 1000
`

type GetExpiredActiveDrugsRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	BatchNumber string    `json:"batch_number"`
	ExpiryDate  time.Time `json:"expiry_date"`
}

func (q *Queries) GetExpiredActiveDrugs(ctx context.Context) ([]GetExpiredActiveDrugsRow, error) {
	rows, err := q.db.Query(ctx, getExpiredActiveDrugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExpiredActiveDrugsRow{}
	for rows.Next() {
		var i GetExpiredActiveDrugsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BatchNumber,
			&i.ExpiryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrugs = `-- name: ListDrugs :many
SELECT d.id, d.name, d.generic_name, d.manufacturer_id, d.batch_number, d.nafdac_number, d.manufacturing_date, d.expiry_date, d.quantity, d.status, d.created_by, d.created_at, d.updated_at,
       m.name AS manufacturer_name
FROM drugs d
JOIN manufacturers m ON d.manufacturer_id = m.id
WHERE
    ($3::text IS NULL OR d.name ILIKE '%' || $3::text || '%')
    AND ($4::text IS NULL OR d.generic_name ILIKE '%' || $4::text || '%')
    AND ($5::text IS NULL OR d.batch_number = $5::text)
    AND ($6::drug_status IS NULL OR d.status = $6::drug_status)
    AND ($7::uuid IS NULL OR d.manufacturer_id = $7::uuid)
    AND ($8::date IS NULL OR d.expiry_date <= $8::date)
    AND ($9::date IS NULL OR d.expiry_date >= $9::date)
ORDER BY d.created_at DESC
LIMIT $1 OFFSET $2
`

type ListDrugsParams struct {
	Limit          int32          `json:"limit"`
	Offset         int32          `json:"offset"`
	Name           pgtype.Text    `json:"name"`
	GenericName    pgtype.Text    `json:"generic_name"`
	BatchNumber    pgtype.Text    `json:"batch_number"`
	Status         NullDrugStatus `json:"status"`
	ManufacturerID pgtype.UUID    `json:"manufacturer_id"`
	ExpiryBefore   pgtype.Date    `json:"expiry_before"`
	ExpiryAfter    pgtype.Date    `json:"expiry_after"`
}

type ListDrugsRow struct {
	ID                uuid.UUID  `json:"id"`
	Name              string     `json:"name"`
	GenericName       string     `json:"generic_name"`
	ManufacturerID    uuid.UUID  `json:"manufacturer_id"`
	BatchNumber       string     `json:"batch_number"`
	NafdacNumber      string     `json:"nafdac_number"`
	ManufacturingDate time.Time  `json:"manufacturing_date"`
	ExpiryDate        time.Time  `json:"expiry_date"`
	Quantity          int32      `json:"quantity"`
	Status            DrugStatus `json:"status"`
	CreatedBy         uuid.UUID  `json:"created_by"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	ManufacturerName  string     `json:"manufacturer_name"`
}

func (q *Queries) ListDrugs(ctx context.Context, arg ListDrugsParams) ([]ListDrugsRow, error) {
	rows, err := q.db.Query(ctx, listDrugs,
		arg.Limit,
		arg.Offset,
		arg.Name,
		arg.GenericName,
		arg.BatchNumber,
		arg.Status,
		arg.ManufacturerID,
		arg.ExpiryBefore,
		arg.ExpiryAfter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDrugsRow{}
	for rows.Next() {
		var i ListDrugsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GenericName,
			&i.ManufacturerID,
			&i.BatchNumber,
			&i.NafdacNumber,
			&i.ManufacturingDate,
			&i.ExpiryDate,
			&i.Quantity,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManufacturerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDrug = `-- name: UpdateDrug :one
UPDATE drugs
SET
    name = $2,
    generic_name = $3,
    batch_number = $4,
    nafdac_number = $5,
    manufacturing_date = $6,
    expiry_date = $7,
    quantity = $8,
    status = $9
WHERE id = $1
RETURNING id, name, generic_name, manufacturer_id, batch_number, nafdac_number, manufacturing_date, expiry_date, quantity, status, created_by, created_at, updated_at
`

type UpdateDrugParams struct {
	ID                uuid.UUID  `json:"id"`
	Name              string     `json:"name"`
	GenericName       string     `json:"generic_name"`
	BatchNumber       string     `json:"batch_number"`
	NafdacNumber      string     `json:"nafdac_number"`
	ManufacturingDate time.Time  `json:"manufacturing_date"`
	ExpiryDate        time.Time  `json:"expiry_date"`
	Quantity          int32      `json:"quantity"`
	Status            DrugStatus `json:"status"`
}

func (q *Queries) UpdateDrug(ctx context.Context, arg UpdateDrugParams) (Drug, error) {
	row := q.db.QueryRow(ctx, updateDrug,
		arg.ID,
		arg.Name,
		arg.GenericName,
		arg.BatchNumber,
		arg.NafdacNumber,
		arg.ManufacturingDate,
		arg.ExpiryDate,
		arg.Quantity,
		arg.Status,
	)
	var i Drug
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GenericName,
		&i.ManufacturerID,
		&i.BatchNumber,
		&i.NafdacNumber,
		&i.ManufacturingDate,
		&i.ExpiryDate,
		&i.Quantity,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDrugStatus = `-- name: UpdateDrugStatus :one
UPDATE drugs
SET status = $2
WHERE id = $1
RETURNING id, name, generic_name, manufacturer_id, batch_number, nafdac_number, manufacturing_date, expiry_date, quantity, status, created_by, created_at, updated_at
`

type UpdateDrugStatusParams struct {
	ID     uuid.UUID  `json:"id"`
	Status DrugStatus `json:"status"`
}

func (q *Queries) UpdateDrugStatus(ctx context.Context, arg UpdateDrugStatusParams) (Drug, error) {
	row := q.db.QueryRow(ctx, updateDrugStatus, arg.ID, arg.Status)
	var i Drug
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GenericName,
		&i.ManufacturerID,
		&i.BatchNumber,
		&i.NafdacNumber,
		&i.ManufacturingDate,
		&i.ExpiryDate,
		&i.Quantity,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
