// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manufacturers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countManufacturers = `-- name: CountManufacturers :one
SELECT count(*) FROM manufacturers
`

func (q *Queries) CountManufacturers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countManufacturers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createManufacturer = `-- name: CreateManufacturer :one
INSERT INTO manufacturers (name, address)
VALUES ($1, $2)
RETURNING id, name, address, created_at, updated_at
`

type CreateManufacturerParams struct {
	Name    string `json:"name"`
	Address string `json:"address"`
}

func (q *Queries) CreateManufacturer(ctx context.Context, arg CreateManufacturerParams) (Manufacturer, error) {
	row := q.db.QueryRow(ctx, createManufacturer, arg.Name, arg.Address)
	var i Manufacturer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteManufacturer = `-- name: DeleteManufacturer :exec
DELETE FROM manufacturers WHERE id = $1
`

func (q *Queries) DeleteManufacturer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteManufacturer, id)
	return err
}

const getManufacturer = `-- name: GetManufacturer :one
SELECT id, name, address, created_at, updated_at
FROM manufacturers
WHERE id = $1
`

func (q *Queries) GetManufacturer(ctx context.Context, id uuid.UUID) (Manufacturer, error) {
	row := q.db.QueryRow(ctx, getManufacturer, id)
	var i Manufacturer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManufacturerByName = `-- name: GetManufacturerByName :one
SELECT id, name, address, created_at, updated_at
FROM manufacturers
WHERE name = $1
`

func (q *Queries) GetManufacturerByName(ctx context.Context, name string) (Manufacturer, error) {
	row := q.db.QueryRow(ctx, getManufacturerByName, name)
	var i Manufacturer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listManufacturers = `-- name: ListManufacturers :many
SELECT id, name, address, created_at, updated_at
FROM manufacturers
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListManufacturersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListManufacturers(ctx context.Context, arg ListManufacturersParams) ([]Manufacturer, error) {
	rows, err := q.db.Query(ctx, listManufacturers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Manufacturer{}
	for rows.Next() {
		var i Manufacturer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateManufacturer = `-- name: UpdateManufacturer :one
UPDATE manufacturers
SET name = $2, address = $3
WHERE id = $1
RETURNING id, name, address, created_at, updated_at
`

type UpdateManufacturerParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Address string    `json:"address"`
}

func (q *Queries) UpdateManufacturer(ctx context.Context, arg UpdateManufacturerParams) (Manufacturer, error) {
	row := q.db.QueryRow(ctx, updateManufacturer, arg.ID, arg.Name, arg.Address)
	var i Manufacturer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
