// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DrugStatus string

const (
	DrugStatusActive    DrugStatus = "active"
	DrugStatusExpired   DrugStatus = "expired"
	DrugStatusRecalled  DrugStatus = "recalled"
	DrugStatusSuspended DrugStatus = "suspended"
)

func (e *DrugStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DrugStatus(s)
	case string:
		*e = DrugStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DrugStatus: %T", src)
	}
	return nil
}

type NullDrugStatus struct {
	DrugStatus DrugStatus `json:"drug_status"`
	Valid      bool       `json:"valid"` // Valid is true if DrugStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDrugStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DrugStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DrugStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDrugStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DrugStatus), nil
}

type DrugUnitStatus string

const (
	DrugUnitStatusActive    DrugUnitStatus = "active"
	DrugUnitStatusUsed      DrugUnitStatus = "used"
	DrugUnitStatusRecalled  DrugUnitStatus = "recalled"
	DrugUnitStatusSuspended DrugUnitStatus = "suspended"
)

func (e *DrugUnitStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DrugUnitStatus(s)
	case string:
		*e = DrugUnitStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DrugUnitStatus: %T", src)
	}
	return nil
}

type NullDrugUnitStatus struct {
	DrugUnitStatus DrugUnitStatus `json:"drug_unit_status"`
	Valid          bool           `json:"valid"` // Valid is true if DrugUnitStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDrugUnitStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DrugUnitStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DrugUnitStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDrugUnitStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DrugUnitStatus), nil
}

type UserRole string

const (
	UserRolePharmacist UserRole = "pharmacist"
	UserRoleAdmin      UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VerificationResult string

const (
	VerificationResultVerified  VerificationResult = "verified"
	VerificationResultNotFound  VerificationResult = "not_found"
	VerificationResultExpired   VerificationResult = "expired"
	VerificationResultRecalled  VerificationResult = "recalled"
	VerificationResultSuspended VerificationResult = "suspended"
	VerificationResultInvalid   VerificationResult = "invalid"
)

func (e *VerificationResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationResult(s)
	case string:
		*e = VerificationResult(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationResult: %T", src)
	}
	return nil
}

type NullVerificationResult struct {
	VerificationResult VerificationResult `json:"verification_result"`
	Valid              bool               `json:"valid"` // Valid is true if VerificationResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationResult) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationResult), nil
}

type Drug struct {
	ID                uuid.UUID  `json:"id"`
	Name              string     `json:"name"`
	GenericName       string     `json:"generic_name"`
	ManufacturerID    uuid.UUID  `json:"manufacturer_id"`
	BatchNumber       string     `json:"batch_number"`
	NafdacNumber      string     `json:"nafdac_number"`
	ManufacturingDate time.Time  `json:"manufacturing_date"`
	ExpiryDate        time.Time  `json:"expiry_date"`
	Quantity          int32      `json:"quantity"`
	Status            DrugStatus `json:"status"`
	CreatedBy         uuid.UUID  `json:"created_by"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

type DrugUnit struct {
	ID           uuid.UUID      `json:"id"`
	DrugID       uuid.UUID      `json:"drug_id"`
	SerialNumber string         `json:"serial_number"`
	Status       DrugUnitStatus `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Manufacturer struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	FullName     string    `json:"full_name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         UserRole  `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type VerificationLog struct {
	ID           uuid.UUID          `json:"id"`
	DrugUnitID   pgtype.UUID        `json:"drug_unit_id"`
	SerialNumber string             `json:"serial_number"`
	Verified     bool               `json:"verified"`
	Result       VerificationResult `json:"result"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	VerifiedAt   time.Time          `json:"verified_at"`
}
