// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountDrugUnitsByDrug(ctx context.Context, drugID uuid.UUID) (int64, error)
	CountDrugs(ctx context.Context, arg CountDrugsParams) (int64, error)
	CountManufacturers(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountVerificationLogs(ctx context.Context, arg CountVerificationLogsParams) (int64, error)
	CountVerificationLogsByDrug(ctx context.Context, arg CountVerificationLogsByDrugParams) (int64, error)
	CreateDrug(ctx context.Context, arg CreateDrugParams) (Drug, error)
	CreateDrugUnit(ctx context.Context, arg CreateDrugUnitParams) (DrugUnit, error)
	CreateManufacturer(ctx context.Context, arg CreateManufacturerParams) (Manufacturer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateVerificationLog(ctx context.Context, arg CreateVerificationLogParams) (VerificationLog, error)
	DeleteManufacturer(ctx context.Context, id uuid.UUID) error
	GetDrug(ctx context.Context, id uuid.UUID) (GetDrugRow, error)
	GetDrugByManufacturerAndBatch(ctx context.Context, arg GetDrugByManufacturerAndBatchParams) (uuid.UUID, error)
	GetDrugUnit(ctx context.Context, id uuid.UUID) (DrugUnit, error)
	GetDrugUnitBySerial(ctx context.Context, serialNumber string) (GetDrugUnitBySerialRow, error)
	GetExpiredActiveDrugs(ctx context.Context) ([]GetExpiredActiveDrugsRow, error)
	GetManufacturer(ctx context.Context, id uuid.UUID) (Manufacturer, error)
	GetManufacturerByName(ctx context.Context, name string) (Manufacturer, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	ListDrugUnitsByDrug(ctx context.Context, arg ListDrugUnitsByDrugParams) ([]DrugUnit, error)
	ListDrugs(ctx context.Context, arg ListDrugsParams) ([]ListDrugsRow, error)
	ListManufacturers(ctx context.Context, arg ListManufacturersParams) ([]Manufacturer, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListVerificationLogs(ctx context.Context, arg ListVerificationLogsParams) ([]ListVerificationLogsRow, error)
	ListVerificationLogsByDrug(ctx context.Context, arg ListVerificationLogsByDrugParams) ([]ListVerificationLogsByDrugRow, error)
	UpdateDrug(ctx context.Context, arg UpdateDrugParams) (Drug, error)
	UpdateDrugStatus(ctx context.Context, arg UpdateDrugStatusParams) (Drug, error)
	UpdateDrugUnitStatus(ctx context.Context, arg UpdateDrugUnitStatusParams) (DrugUnit, error)
	UpdateManufacturer(ctx context.Context, arg UpdateManufacturerParams) (Manufacturer, error)
}

var _ Querier = (*Queries)(nil)
