// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countVerificationLogs = `-- name: CountVerificationLogs :one
SELECT count(*)
FROM verification_logs vl
WHERE
    ($1::text IS NULL OR vl.serial_number = $1::text)
    AND ($2::verification_result IS NULL OR vl.result = $2::verification_result)
    AND ($3::timestamptz IS NULL OR vl.verified_at >= $3::timestamptz)
    AND ($4::timestamptz IS NULL OR vl.verified_at <= $4::timestamptz)
`

type CountVerificationLogsParams struct {
	SerialNumber pgtype.Text            `json:"serial_number"`
	Result       NullVerificationResult `json:"result"`
	FromDate     pgtype.Timestamptz     `json:"from_date"`
	ToDate       pgtype.Timestamptz     `json:"to_date"`
}

func (q *Queries) CountVerificationLogs(ctx context.Context, arg CountVerificationLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVerificationLogs,
		arg.SerialNumber,
		arg.Result,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVerificationLogsByDrug = `-- name: CountVerificationLogsByDrug :one
SELECT count(*)
FROM verification_logs vl
JOIN drug_units du ON vl.drug_unit_id = du.id
WHERE du.drug_id = $1
    AND ($2::verification_result IS NULL OR vl.result = $2::verification_result)
    AND ($3::timestamptz IS NULL OR vl.verified_at >= $3::timestamptz)
    AND ($4::timestamptz IS NULL OR vl.verified_at <= $4::timestamptz)
`

type CountVerificationLogsByDrugParams struct {
	DrugID   uuid.UUID              `json:"drug_id"`
	Result   NullVerificationResult `json:"result"`
	FromDate pgtype.Timestamptz     `json:"from_date"`
	ToDate   pgtype.Timestamptz     `json:"to_date"`
}

func (q *Queries) CountVerificationLogsByDrug(ctx context.Context, arg CountVerificationLogsByDrugParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVerificationLogsByDrug,
		arg.DrugID,
		arg.Result,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVerificationLog = `-- name: CreateVerificationLog :one
INSERT INTO verification_logs (drug_unit_id, serial_number, verified, result, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, drug_unit_id, serial_number, verified, result, ip_address, user_agent, verified_at
`

type CreateVerificationLogParams struct {
	DrugUnitID   pgtype.UUID        `json:"drug_unit_id"`
	SerialNumber string             `json:"serial_number"`
	Verified     bool               `json:"verified"`
	Result       VerificationResult `json:"result"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
}

func (q *Queries) CreateVerificationLog(ctx context.Context, arg CreateVerificationLogParams) (VerificationLog, error) {
	row := q.db.QueryRow(ctx, createVerificationLog,
		arg.DrugUnitID,
		arg.SerialNumber,
		arg.Verified,
		arg.Result,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i VerificationLog
	err := row.Scan(
		&i.ID,
		&i.DrugUnitID,
		&i.SerialNumber,
		&i.Verified,
		&i.Result,
		&i.IpAddress,
		&i.UserAgent,
		&i.VerifiedAt,
	)
	return i, err
}

const listVerificationLogs = `-- name: ListVerificationLogs :many
SELECT vl.id, vl.drug_unit_id, vl.serial_number, vl.verified, vl.result,
       vl.ip_address, vl.verified_at
FROM verification_logs vl
WHERE
    ($3::text IS NULL OR vl.serial_number = $3::text)
    AND ($4::verification_result IS NULL OR vl.result = $4::verification_result)
    AND ($5::timestamptz IS NULL OR vl.verified_at >= $5::timestamptz)
    AND ($6::timestamptz IS NULL OR vl.verified_at <= $6::timestamptz)
ORDER BY vl.verified_at DESC
LIMIT $1 OFFSET $2
`

type ListVerificationLogsParams struct {
	Limit        int32                  `json:"limit"`
	Offset       int32                  `json:"offset"`
	SerialNumber pgtype.Text            `json:"serial_number"`
	Result       NullVerificationResult `json:"result"`
	FromDate     pgtype.Timestamptz     `json:"from_date"`
	ToDate       pgtype.Timestamptz     `json:"to_date"`
}

type ListVerificationLogsRow struct {
	ID           uuid.UUID          `json:"id"`
	DrugUnitID   pgtype.UUID        `json:"drug_unit_id"`
	SerialNumber string             `json:"serial_number"`
	Verified     bool               `json:"verified"`
	Result       VerificationResult `json:"result"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	VerifiedAt   time.Time          `json:"verified_at"`
}

func (q *Queries) ListVerificationLogs(ctx context.Context, arg ListVerificationLogsParams) ([]ListVerificationLogsRow, error) {
	rows, err := q.db.Query(ctx, listVerificationLogs,
		arg.Limit,
		arg.Offset,
		arg.SerialNumber,
		arg.Result,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVerificationLogsRow{}
	for rows.Next() {
		var i ListVerificationLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.DrugUnitID,
			&i.SerialNumber,
			&i.Verified,
			&i.Result,
			&i.IpAddress,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationLogsByDrug = `-- name: ListVerificationLogsByDrug :many
SELECT vl.id, vl.drug_unit_id, vl.serial_number, vl.verified, vl.result,
       vl.ip_address, vl.verified_at
FROM verification_logs vl
JOIN drug_units du ON vl.drug_unit_id = du.id
WHERE du.drug_id = $1
    AND ($4::verification_result IS NULL OR vl.result = $4::verification_result)
    AND ($5::timestamptz IS NULL OR vl.verified_at >= $5::timestamptz)
    AND ($6::timestamptz IS NULL OR vl.verified_at <= $6::timestamptz)
ORDER BY vl.verified_at DESC
LIMIT $2 OFFSET $3
`

type ListVerificationLogsByDrugParams struct {
	DrugID   uuid.UUID              `json:"drug_id"`
	Limit    int32                  `json:"limit"`
	Offset   int32                  `json:"offset"`
	Result   NullVerificationResult `json:"result"`
	FromDate pgtype.Timestamptz     `json:"from_date"`
	ToDate   pgtype.Timestamptz     `json:"to_date"`
}

type ListVerificationLogsByDrugRow struct {
	ID           uuid.UUID          `json:"id"`
	DrugUnitID   pgtype.UUID        `json:"drug_unit_id"`
	SerialNumber string             `json:"serial_number"`
	Verified     bool               `json:"verified"`
	Result       VerificationResult `json:"result"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	VerifiedAt   time.Time          `json:"verified_at"`
}

func (q *Queries) ListVerificationLogsByDrug(ctx context.Context, arg ListVerificationLogsByDrugParams) ([]ListVerificationLogsByDrugRow, error) {
	rows, err := q.db.Query(ctx, listVerificationLogsByDrug,
		arg.DrugID,
		arg.Limit,
		arg.Offset,
		arg.Result,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVerificationLogsByDrugRow{}
	for rows.Next() {
		var i ListVerificationLogsByDrugRow
		if err := rows.Scan(
			&i.ID,
			&i.DrugUnitID,
			&i.SerialNumber,
			&i.Verified,
			&i.Result,
			&i.IpAddress,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
